#pragma once

#define IDR_REX_TOOLKIT_LOGO 101
#define IDR_AUTO_CLICKER_ICON 102
#define IDR_FILE_CONVERTER_ICON 103
#define IDR_MEDIA_DOWNLOADER_ICON 104
#define IDR_ALL_TOOLS_ICON 105
#define IDR_SETTINGS_ICON 106
#define IDR_REMINDERS_ICON 107
#define IDR_SMART_FILE_TRANSFER_ICON 108
#define IDR_MACRO_RECORDER_ICON 109
#define IDR_VIDEO_COMPRESSOR_ICON 110
#define IDR_MEDIA_EDITOR_ICON 111
#define IDR_MEDIA_EDITOR_ERASER_ICON 112
#define IDR_GALLERY_ICON 113
#define IDR_CUSTOM_IMAGE_ICON 114
#define IDI_REX_TOOLKIT_ICON 201
