#pragma once

#define IDR_REX_TOOLKIT_LOGO 101
#define IDR_AUTO_CLICKER_ICON 102
#define IDR_FILE_CONVERTER_ICON 103
#define IDR_MEDIA_DOWNLOADER_ICON 104
#define IDR_ALL_TOOLS_ICON 105
#define IDR_SETTINGS_ICON 106
#define IDI_REX_TOOLKIT_ICON 201
